In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

Matplotlib is building the font cache; this may take a moment.

In [2]:
df = pd.read_csv('CO2 Emissions_Canada.csv')
print(df.columns)

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)', 'Legal Limit'],
      dtype='object')

In [3]:
#Creating a column of 1's and 0's
threshold = 245 #g/km
df['Legal Limit'] = df['CO2 Emissions(g/km)'].apply(lambda x: 1 if x <= threshold else 0)
df.to_csv("CO2 Emissions_Canada.csv", index=False)
print(df.columns)

Index(['Make', 'Model', 'Vehicle Class', 'Engine Size(L)', 'Cylinders',
       'Transmission', 'Fuel Type', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)', 'Legal Limit'],
      dtype='object')

In [4]:
df.drop(['Make', 'Model', 'Vehicle Class', 'Transmission'], axis=1, errors='ignore', inplace=True)
df.head()

,Engine Size(L),Cylinders,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Legal Limit
0,2.0,4,Z,9.9,6.7,8.5,33,196,1
1,2.4,4,Z,11.2,7.7,9.6,29,221,1
2,1.5,4,Z,6.0,5.8,5.9,48,136,1
3,3.5,6,Z,12.7,9.1,11.1,25,255,0
4,3.5,6,Z,12.1,8.7,10.6,27,244,1

In [5]:
df_encoded = pd.get_dummies(df, columns=['Fuel Type'], prefix='', prefix_sep='', drop_first=True)
df_encoded = df_encoded.astype(int)
df_encoded.head()

,Engine Size(L),Cylinders,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),Fuel Consumption Comb (mpg),CO2 Emissions(g/km),Legal Limit,E,N,X,Z
0,2,4,9,6,8,33,196,1,0,0,0,1
1,2,4,11,7,9,29,221,1,0,0,0,1
2,1,4,6,5,5,48,136,1,0,0,0,1
3,3,6,12,9,11,25,255,0,0,0,0,1
4,3,6,12,8,10,27,244,1,0,0,0,1

In [6]:
print(df_encoded.columns)
X = df_encoded[['Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'E', 'N', 'X',
       'Z']]
Y = df_encoded['Legal Limit'].values

Index(['Engine Size(L)', 'Cylinders', 'Fuel Consumption City (L/100 km)',
       'Fuel Consumption Hwy (L/100 km)', 'Fuel Consumption Comb (L/100 km)',
       'Fuel Consumption Comb (mpg)', 'CO2 Emissions(g/km)', 'Legal Limit',
       'E', 'N', 'X', 'Z'],
      dtype='object')

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20, random_state = 42)
X_train = StandardScaler().fit_transform(X_train)
X_test = StandardScaler().fit_transform(X_test)

In [8]:
from sklearn.linear_model import LogisticRegression
logisticregression = LogisticRegression()
logisticregression.fit(X_train, Y_train)

LogisticRegression()

In [9]:
Y_pred = logisticregression.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score, precision_score
accuracy = accuracy_score(Y_test, Y_pred)
precision = precision_score(Y_test, Y_pred)
recall = recall_score(Y_test, Y_pred)
f1 = f1_score(Y_test, Y_pred)

print(f'Accuracy: {accuracy:.2f}')
print(f'Precision: {precision:.2f}')
print(f'Recall: {recall:.2f}')
print(f'F1 Score: {f1:.2f}')

Accuracy: 0.97
Precision: 1.00
Recall: 0.95
F1 Score: 0.97

In [ ]:
##PLOT

In [ ]:
##Ccomparision